# Declare variables to be passed into your templates.
mybb:
  replicas: 3
  port: 80
  image:
    repository: docker.for.mac.localhost:5000/mybb
    tag: 5_helm
php:
  database:
    driver: mysqli
mysql:
  hostname: database-mysql.default.svc.cluster.local
  schema:
    name: mybb
    table_prefix: mybb_
    encoding: utf8
  credentials:
    username: mybb
    password: mybb
cache:
  store: memcached
  memcache:
    host: cache-memcached.default.svc.cluster.local
    port: 11211
board:
    closed:
      is_closed: 0
      reason: These forums are currently closed for maintenance. Please check back later.
