apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybb-deployment
  labels:
    app: mybb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mybb
  template:
    metadata:
      labels:
        app: mybb
    spec:
      containers:
      - name: mybb
        image: docker.io/magickatt/mybb:2_noconfig
        ports:
        - containerPort: 80
        volumeMounts:
        - name: mybb-volume
          mountPath: /var/config/mybb
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: mybb-volume
        configMap:
          name: mybb-configmap
          items:
          - key: config.php
            path: config.php
          - key: settings.php
            path: settings.php

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mybb
  name: mybb-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mybb
  type: LoadBalancer
