apiVersion: v1
kind: Service
metadata:
  labels:
    app: mybb
  name: mybb-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: {{ .Values.mybb.port }}
  selector:
    app: mybb
  type: LoadBalancer
