apiVersion: v1
kind: Service
metadata:
  labels:
    app: mybb
  name: mybb-service
spec:
  ports:
  - port: {{ .Values.mybb.port }}
    protocol: TCP
    targetPort: 80
  selector:
    app: mybb
  type: LoadBalancer
