apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybb-deployment
  labels:
    app: mybb
spec:
  replicas: {{ .Values.mybb.replicas }}
  selector:
    matchLabels:
      app: mybb
  template:
    metadata:
      labels:
        app: mybb
    spec:
      containers:
      - name: mybb
        image: "{{- .Values.mybb.image.repository -}}:{{- .Values.mybb.image.tag }}"
        ports:
        - containerPort: {{ .Values.mybb.port }}
        volumeMounts:
        - name: mybb-volume
          mountPath: /var/config/mybb
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: mybb-volume
        configMap:
          name: mybb-config
          items:
          - key: config.php
            path: config.php
          - key: settings.php
            path: settings.php
