# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mybb-deployment
#   labels:
#     app: mybb
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mybb
#   template:
#     metadata:
#       labels:
#         app: mybb
#     spec:
#       containers:
#       - name: mybb
#         image: docker.io/magickatt/mybb:latest
#         ports:
#         - containerPort: 80


apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybb-deployment
  labels:
    app: mybb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mybb
  template:
    metadata:
      labels:
        app: mybb
    spec:
      containers:
      - name: mybb
        image: docker.io/magickatt/mybb:2_noconfig
        ports:
        - containerPort: 80
        volumeMounts:
        - name: mybb-volume
          mountPath: /var/config/mybb
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: mybb-volume
        configMap:
          name: mybb-configmap
          items:
          - key: config.php
            path: config.php
          - key: settings.php
            path: settings.php
