# Minimum version required for Docker Swarm compatibility and configs feature
version: "3.3"

services:
  # MyBB
  mybb:
    image: magickatt/mybb:2_compose
    volumes:
      - ../configuration:/var/config/mybb
    ports:
      - "80:80"
    networks:
      - default

  # MySQL
  database:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    networks:
      - default

networks:
  default:
