# Declare variables to be passed into your templates.
mybb:
  replicas: 3
  port: 80
  image:
    repository: host.docker.internal:5000/mybb
    tag: 6_dynamic
consul:
  host: consul-server-0.consul-server.default.svc
  port: 8500
vault:
  host: http://secrets-vault
  port: 8200
