# Declare variables to be passed into your templates.
mybb:
  replicas: 3
  port: 80
  image:
    repository: docker.io/magickatt/mybb
    tag: 2_compose
php:
  database:
    driver: mysqli
mysql:
  hostname: mybb-mysql.default.svc.cluster.local
  schema:
    name: mybb
    table_prefix: mybb_
    encoding: utf8
  credentials:
    username: mybb
    password: mybb
cache:
  store: db
  memcache:
    host: localhost
    port: 11211
board:
    closed:
      is_closed: 0
      reason: These forums are currently closed for maintenance. Please check back later.
